Lobby:
   World: world
   X: 100
   Y: 100
   Z: 100
   Pitch: 100
   Yaw: 100
Database:
   Host: localhost
   Port: 3306
   Database: db
   User: username
   Password: passy
LobbyServer: Lobby
Arenas: 10
Maps: []
setupmode: true
#do NOT use this in production mode
debug: false
