GameServer: "OneVsOne-1"

#This are the Settings for the MySql or MariaDB Database. A database is required
Database:
  Host: localhost
  Port: 3306
  Database: db
  User: username
  Password: passy
  
Joinsign:
   World: world
   X: 0
   Y: 0
   Z: 0
   Direction: null