GameServer: "OneVsOne-1"

#This are the Settings for the MySql or MariaDB Database. A database is required
Database:
  Host: localhost
  Port: 3306
  Database: db
  User: username
  Password: passy
  
#do NOT enable this in production mode
debug: false