name: OneVsOneLobby
main: com.github.gamedipoxx.oneVsOneLobby.OneVsOneLobby
author: Professor_Sam 
version: 1.2.1
api-version: 1.17
commands:
   onevsonelobby:
      description: "Verwaltet die OneVsOneLobby"